name: Deploy

on:
  push:
    branches:
      - main
env:
  VITE_INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
  
jobs:
  deploy:
    name: Deploy no Hostgator
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Verifica se ocorreu commits recentes
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Gerencia versão do NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instala gerenciador de pacotes e dependências
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@next-7; pnpm install --no-frozen-lockfile
      - name: Inicia Build do projeto
        run: pnpm run build; curl -L --fail https://get.pnpm.io/v6.js > dist/pnpm.js
      - name: Sincroniza com o servidor
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: ./dist/
          server-dir: public_html/
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
